CREATE TABLE wallets (
player_id VARCHAR(50) PRIMARY KEY,
balance INTEGER NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE wallets
ADD CONSTRAINT balance_non_negative
CHECK (balance >= 0);

CREATE TABLE transactions (
id SERIAL PRIMARY KEY,
player_id VARCHAR(50) NOT NULL,
type VARCHAR(20) NOT NULL,
amount INTEGER NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory (
id SERIAL PRIMARY KEY,
player_id VARCHAR(50) NOT NULL,
item_id VARCHAR(100) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reward_claims (
id SERIAL PRIMARY KEY,
player_id VARCHAR(50) NOT NULL,
reward_id VARCHAR(100) NOT NULL,
claimed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UNIQUE(player_id, reward_id)
);

CREATE TABLE idempotency_keys (
id VARCHAR(255) PRIMARY KEY,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
